# Generated by Django 5.1 on 2026-03-05 03:07

import apps.invites.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInvite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(default=apps.invites.models.generate_token, max_length=128, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('used', 'Used'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='pending', max_length=10)),
                ('expires_at', models.DateTimeField(default=apps.invites.models.default_expiry)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('used_ip', models.GenericIPAddressField(blank=True, help_text='IP address that redeemed this invite', null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='devices.device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
