# Generated by Django 5.1 on 2026-03-05 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.CharField(default='wg0', max_length=15)),
                ('public_ip', models.GenericIPAddressField(help_text='Your GCP external IP address')),
                ('listen_port', models.PositiveIntegerField(default=51820)),
                ('vpn_subnet', models.CharField(default='10.0.0.0/24', help_text='e.g. 10.0.0.0/24', max_length=20)),
                ('server_ip', models.GenericIPAddressField(default='10.0.0.1', help_text='The server itself inside the VPN e.g. 10.0.0.1')),
                ('public_key', models.TextField(help_text='WireGuard server public key')),
                ('private_key', models.TextField(help_text='Encrypted WireGuard server private key')),
                ('dns_servers', models.CharField(default='1.1.1.1,8.8.8.8', max_length=100)),
                ('mtu', models.PositiveIntegerField(default=1420)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Server Configuration',
            },
        ),
        migrations.CreateModel(
            name='IPAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('status', models.CharField(choices=[('free', 'Free'), ('assigned', 'Assigned'), ('reserved', 'Reserved')], default='free', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_allocations', to='server.serverconfig')),
            ],
            options={
                'ordering': ['ip_address'],
                'unique_together': {('server', 'ip_address')},
            },
        ),
    ]
