# Generated by Django 6.0.3 on 2026-03-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverconfig',
            name='address',
            field=models.CharField(default='10.0.0.1/24', help_text='Server VPN address with mask e.g. 10.0.0.1/24', max_length=20),
        ),
        migrations.AddField(
            model_name='serverconfig',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Only one server can be active at a time'),
        ),
        migrations.AddField(
            model_name='serverconfig',
            name='name',
            field=models.CharField(default='Primary Server', help_text='A friendly name e.g. GCP Primary', max_length=100),
        ),
        migrations.AddField(
            model_name='serverconfig',
            name='post_down',
            field=models.TextField(default='iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE'),
        ),
        migrations.AddField(
            model_name='serverconfig',
            name='post_up',
            field=models.TextField(default='iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE'),
        ),
        migrations.AddField(
            model_name='serverconfig',
            name='ssh_host',
            field=models.CharField(blank=True, help_text='GCP server external IP', max_length=255),
        ),
        migrations.AddField(
            model_name='serverconfig',
            name='ssh_key_path',
            field=models.CharField(default='gcp_key', max_length=500),
        ),
        migrations.AddField(
            model_name='serverconfig',
            name='ssh_user',
            field=models.CharField(default='electrical', max_length=100),
        ),
        migrations.AlterField(
            model_name='serverconfig',
            name='private_key',
            field=models.TextField(blank=True, help_text='Encrypted WireGuard server private key'),
        ),
        migrations.AlterField(
            model_name='serverconfig',
            name='server_ip',
            field=models.GenericIPAddressField(default='10.0.0.1'),
        ),
        migrations.AlterField(
            model_name='serverconfig',
            name='vpn_subnet',
            field=models.CharField(default='10.0.0.0/24', max_length=20),
        ),
    ]
