# Generated by Django 6.0.3 on 2026-03-07 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_serverconfig_address_serverconfig_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverconfig',
            name='is_active',
        ),
    ]
