# Generated by Django 6.0.3 on 2026-03-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_remove_serverconfig_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverconfig',
            name='ssh_key_encrypted',
            field=models.TextField(blank=True, help_text='Encrypted SSH private key content'),
        ),
    ]
