# Generated by Django 6.0.3 on 2026-03-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_serverconfig_ssh_key_encrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverconfig',
            name='gcp_instance_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='serverconfig',
            name='gcp_project_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='serverconfig',
            name='gcp_zone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='serverconfig',
            name='provisioning_log',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='serverconfig',
            name='provisioning_status',
            field=models.CharField(choices=[('manual', 'Manually Configured'), ('provisioning', 'Provisioning'), ('provisioned', 'Provisioned'), ('failed', 'Failed')], default='manual', max_length=15),
        ),
        migrations.AlterField(
            model_name='serverconfig',
            name='public_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Your GCP external IP address', null=True),
        ),
        migrations.AlterField(
            model_name='serverconfig',
            name='public_key',
            field=models.TextField(blank=True, help_text='WireGuard server public key'),
        ),
    ]
