# Generated by Django 6.0.3 on 2026-03-25 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_serverconfig_gcp_instance_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverconfig',
            name='aws_instance_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='serverconfig',
            name='aws_region',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
