# Generated by Django 6.0.3 on 2026-03-26 00:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_serverconfig_aws_instance_id_serverconfig_aws_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerHealthStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_up', models.BooleanField(default=True)),
                ('checked_at', models.DateTimeField(auto_now=True)),
                ('alerted_at', models.DateTimeField(blank=True, null=True)),
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_status', to='server.serverconfig')),
            ],
        ),
    ]
