# Generated by Django 5.1 on 2026-03-05 03:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('server', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g. John's iPhone", max_length=100)),
                ('device_type', models.CharField(choices=[('laptop', 'Laptop'), ('phone', 'Phone'), ('tablet', 'Tablet'), ('server', 'Server'), ('other', 'Other')], default='other', max_length=10)),
                ('public_key', models.TextField(unique=True)),
                ('private_key_encrypted', models.TextField(blank=True, help_text='AES encrypted private key')),
                ('preshared_key_encrypted', models.TextField(blank=True, help_text='AES encrypted preshared key')),
                ('status', models.CharField(choices=[('active', 'Active'), ('disabled', 'Disabled'), ('revoked', 'Revoked')], default='active', max_length=10)),
                ('last_handshake', models.DateTimeField(blank=True, null=True)),
                ('bytes_sent', models.BigIntegerField(default=0)),
                ('bytes_received', models.BigIntegerField(default=0)),
                ('imported', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocated_ip', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='device', to='server.ipallocation')),
                ('user', models.ForeignKey(blank=True, help_text='Leave blank for unassigned imported devices', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='users.vpnuser')),
            ],
            options={
                'verbose_name': 'Device',
                'ordering': ['name'],
            },
        ),
    ]
