# Generated by Django 6.0.3 on 2026-03-06 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('server', '0002_serverconfig_address_serverconfig_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='server.serverconfig'),
        ),
    ]
